### ISSUE TITLE
Unable to access bookstack

### ISSUE THREAD

**Issue by FaserF** [hassio-addons/addon-bookstack#10]
# Problem/Motivation

> I am unable to access the bookstack webpage after installing the addon

## Expected behavior

> Access the bookstack page over port 2665

## Actual behavior

> Error: "This site doesnt work"

## Steps to reproduce

> I have tried using the config with and without ssl, both without success.
{
  "database_location": "local",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## Error Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 31-mysql: applying... 
[fix-attrs.d] 31-mysql: exited 0.
[fix-attrs.d] 33-bookstack: applying... 
[fix-attrs.d] 33-bookstack: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Bookstack
 A platform for organising and storing information
-----------------------------------------------------------
 Add-on version: 035bffe
 You are running the latest version of this add-on.
 System: HassOS 3.8  (armv7 / tinker)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] bookstack.sh: executing... 
[cont-init.d] bookstack.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:07:02] INFO: Starting MySQL...
200125 12:07:03 mysqld_safe Logging to '/data/mysql/log.err'.
200125 12:07:03 mysqld_safe Starting mysqld daemon with databases from /data/mysql
[12:07:05] INFO: Installing/updating Database
                                                                               
  [UnexpectedValueException]                                                   
  The stream or file "/var/www/bookstack/storage/logs/laravel.log" could not   
  be opened: failed to open stream: No such file or directory                  
                                                                               
[12:07:08] INFO: Starting PHP-FPM...
[12:07:08] INFO: Starting NGinx...
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/servers/direct.conf:8
2020/01/25 12:08:02 [error] 1491#1491: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=lo...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connec
[25/Jan/2020:12:08:02 +0100] 500 -(192.168.178.10) GET / HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
2020/01/25 12:11:30 [error] 1491#1491: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=lo...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'bookstack', 'bookstack', Array)
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connec
[25/Jan/2020:12:11:30 +0100] 500 -(84.56.247.102) GET / HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36)
```

**Comment by sinclairpaul** [comment]
Looks to me that mysql failed to setup correctly.  Can you uninstall the addon and re-install, posting the log when it first starts.

**Comment by sinclairpaul** [comment]
I duplicated the issue and have checked in a fix, you will need to uninstall and reinstall the add on once it is updated.  

It is likely that we will remove the MySQL component completely from the add on itself, so please consider this when testing.

**Comment by FaserF** [comment]
Awesome, now it's working! Thank you so much for that fast support
