### ISSUE TITLE
Update to 1.6.0 throws an error

### ISSUE THREAD

**Issue by dm82m** [hassio-addons/addon-bookstack#210]
# Problem/Motivation

> Update throws an error.

## Expected behavior

> update runs without error.

## Actual behavior

> 
![DCC564A1-0AB7-436F-9786-385CE8760866](https://user-images.githubusercontent.com/736311/221769037-c5623e63-4d26-40bd-bae2-20ab4eb45fe9.png)

## Steps to reproduce

> click „install“

## Proposed changes

> maybe it’s a timing issue, so that the image takes more than 3 hours to be available in the repo!?

**Comment by flexorflex** [comment]
Same ![Uploading 6381AFBA-F220-4B93-934A-D9226358A3F0.jpeg…]()

**Comment by flexorflex** [comment]
![69B029DB-E5C1-4943-B7AD-077AD6D8B1E3](https://user-images.githubusercontent.com/10441182/221769890-aebd7047-ded6-4a50-8af3-3dcaba204eb7.jpeg)
![B0A4402D-3A8D-4958-AE57-8E13EB91B31E](https://user-images.githubusercontent.com/10441182/221769893-0b265499-2a89-44cf-ad1f-8967df535403.jpeg)
![86FECBC5-B8AE-45F9-9C88-8A055B9BDF28](https://user-images.githubusercontent.com/10441182/221769899-8b8982e7-3874-46e1-ab2a-be0b56e0386a.jpeg)
![8180EB77-92F5-4DBC-8756-8CFDB8005055](https://user-images.githubusercontent.com/10441182/221769902-0ab9f0e4-2f2a-4e2f-84e6-4253110fa280.png)
![F870548C-2921-46B0-8909-642593766BE4](https://user-images.githubusercontent.com/10441182/221769903-29ec8574-48a7-4e41-af9a-ca3de79e9d27.png)
![54193AA7-6B5C-40A4-B4B6-5E1692C13D46](https://user-images.githubusercontent.com/10441182/221769904-9df9a927-b254-48db-ab18-ad574bedf27c.jpeg)
![82BCCF00-C436-4CC7-8421-AFFB73AF55FF](https://user-images.githubusercontent.com/10441182/221769908-22c1afd8-a94e-4793-b7f0-70a46118e159.jpeg)
![76131AE5-8393-46EF-9296-CD26B22CAD4D](https://user-images.githubusercontent.com/10441182/221769909-98e3cb0b-8bfd-46ac-8869-745c9b22fb40.jpeg)
![23B4CDC6-AA7A-4673-9D0D-D2037E7FE7C1](https://user-images.githubusercontent.com/10441182/221769918-0d5afd4f-8e60-46fd-9b09-89deb7fae991.png)

**Comment by dm82m** [comment]
Clean your post, a lot of private pictures made their way into it.

**Comment by flexorflex** [comment]
![DFBE5B7C-EC15-4917-80C3-68D9AFA0E182](https://user-images.githubusercontent.com/10441182/221771703-9340db60-dc15-43a2-80ba-12161b5e8a6d.png)

**Comment by enviousjag** [comment]
Same issue here.

**Comment by beta-j** [comment]
Same issue here.  Log file output:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:12:55 (1 occurrences)
Last logged: 10:12:55

[547409630432] Error updating Bookstack: Can't install ghcr.io/hassio-addons/bookstack/aarch64:1.6.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.0&fromImage=ghcr.io%2Fhassio-addons%2Fbookstack%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/hassio-addons/bookstack/aarch64:1.6.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.0&fromImage=ghcr.io%2Fhassio-addons%2Fbookstack%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Bookstack: Can't install ghcr.io/hassio-addons/bookstack/aarch64:1.6.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.0&fromImage=ghcr.io%2Fhassio-addons%2Fbookstack%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")`

**Comment by dm82m** [comment]
the deployment job was not successful, therefore no image available: https://github.com/hassio-addons/addon-bookstack/actions/runs/4289014226

@sinclairpaul needs to check that.

**Comment by sinclairpaul** [comment]
Pushed another release, please try with the latest.

**Comment by dm82m** [comment]
works, thank you!
